Mirandas-Cinema/Mirandas-Cinema/Controllers/ActorsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mirandas_Cinema.Data;
using Mirandas_Cinema.Data.Services;
using Mirandas_Cinema.Data.Static;
using Mirandas_Cinema.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mirandas_Cinema.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ActorsController : Controller
    {
        private readonly IActors service;

        public  ActorsController(IActors _service)
        {
            service = _service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var actors = await service.GetAll();
            return View(actors);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfilePictureURL, FullName, Bio")]Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }

            else
            {
                await service.Add(actor);
                return RedirectToAction(nameof(Index));
            }
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var details = await service.GetById(id);

            if (details == null) 
                return View("NotFound");
            else
                return View(details);
        }

        public async Task<IActionResult> Update(int id)
        {
            var updateDetails = await service.GetById(id);

            if (updateDetails == null)
                return View("NotFound");
            else
                return View(updateDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, [Bind("Id, ProfilePictureURL, FullName, Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }

            else
            {
                await service.Update(id, actor);
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var deleteDetails = await service.GetById(id);

            if (deleteDetails == null)
                return View("NotFound");
            else
                return View(deleteDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actor = await service.GetById(id);
            if (actor == null) return View("NotFound");

            await service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Mirandas-Cinema/Mirandas-Cinema/Controllers/CinemasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mirandas_Cinema.Data;
using Mirandas_Cinema.Data.Services;
using Mirandas_Cinema.Data.Static;
using Mirandas_Cinema.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mirandas_Cinema.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CinemasController : Controller
    {
        private readonly ICinema icinema; 

        public CinemasController(ICinema _cinema)
        {
            icinema = _cinema;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var cinemas = await icinema.GetAll();
            return View(cinemas);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo, Name, Description")] Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }
            else
            {
                await icinema.Add(cinema);
                return RedirectToAction(nameof(Index));
            }
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var details = await icinema.GetById(id);

            if(details == null)
            {
                return View("NotFound");
            }
            else
            {
                return View(details);
            }
        }
        public async Task<IActionResult> Update(int id)
        {
            var updateDetails = await icinema.GetById(id);

            if (updateDetails == null)
            {
                return View("NotFound");
            }
            else
            {
                return View(updateDetails);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id,[Bind("Id, Logo, Name, Description")] Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }
            else
            {
                await icinema.Update(id, cinema);
                return RedirectToAction(nameof(Index));
            }
        }
        public async Task<IActionResult> Delete(int id)
        {
            var deleteDetails = await icinema.GetById(id);
            if (deleteDetails == null)
                return View("NoyFound");
            else
                return View(deleteDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var delete = await icinema.GetById(id);
            if (delete == null) return View("NotFound");

            await icinema.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }


}

Mirandas-Cinema/Mirandas-Cinema/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mirandas_Cinema.Data;
using Mirandas_Cinema.Data.Services;
using Mirandas_Cinema.Data.Static;
using Mirandas_Cinema.Data.ViewModels;
using Mirandas_Cinema.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mirandas_Cinema.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class MoviesController : Controller
    {
        private readonly AppDbContext context;
        private IMovies service;

        public MoviesController(AppDbContext _context, IMovies _service)
        {
            context = _context;
            service = _service;
        }

        public ActionResult ControlMovies()
        {
            var peliculas = service.GetMovies();
            return View(peliculas);
        }

        public ActionResult ControlMovie(int interruptor)
        {
            string url = "";
            if (interruptor == 0)
            {
                url = "/Movies/Create";
            }
            return Redirect(url);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(string searchInvalid, List<Movie> filter)
        {
            var movies = await service.GetAll(n => n.Cinema);
            FiltrarMoviesCaroucel(movies.ToList());

            //para no mostrar los caroucel si no hay resultados
            if (searchInvalid != null && filter.Count == 0)
            {
                movies = filter;
                ViewBag.searchInvalid = searchInvalid;
                FiltrarMoviesCaroucel(filter);

                return View(filter);
            }

            return View(movies);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchMovie)
        {
            var movies = await service.GetAll(n => n.Cinema, n => n.Producer);

            if (!string.IsNullOrEmpty(searchMovie))
            {
                //var filter = movies.Where(m => m.Name.ToLower().Contains(searchMovie.ToLower())
                //    || m.Description.ToLower().Contains(searchMovie.ToLower())
                //    || m.Producer.FullName.ToLower().Contains(searchMovie.ToLower())).ToList();

                var filter = movies.Where(m => string.Equals(m.Name, searchMovie,
                    StringComparison.CurrentCultureIgnoreCase) || string.Equals(m.Description, searchMovie,
                    StringComparison.CurrentCultureIgnoreCase) || string.Equals(m.Producer.FullName, searchMovie,
                    StringComparison.CurrentCultureIgnoreCase)).ToList();

                FiltrarMoviesCaroucel(filter);

                if (filter.Count == 0)
                {
                    await Index("No se encontraron resultados...", filter);
                }

                return View("Index", filter);
            }
            return View("Index", movies);
        }

        //Categorias del menu

        [AllowAnonymous]
        public async Task<IActionResult> Categorias(string categoria)
        {
            var movies = await service.GetAll(n => n.Cinema, n => n.Producer);

            //Accion
            if (!categoria.Equals(""))
            {
                var filter = movies.Where(m => m.MovieCategory.GetHashCode()==Convert.ToInt32(categoria)).ToList();

                FiltrarMoviesCaroucel(filter);

                if (filter.Count == 0)
                {
                    await Index("No se encontraron resultados...", filter);
                }

                return View("Index", filter);
            }
            return View("Index", movies);
        }

        //metodo para hacer un filtro en los carouceles y no mostrarlos si en un caroucel no hay peliculas
        public void FiltrarMoviesCaroucel(List<Movie> filter)
        {
            ViewBag.EnCines = false;
            var consulta1 = (from t in filter
                             where DateTime.Now >= t.StartDate && DateTime.Now <= t.EndDate
                             select t).ToList();

            ViewBag.Expiraron = false;
            var consulta2 = (from t in filter
                             where DateTime.Now > t.StartDate && DateTime.Now > t.EndDate
                             select t).ToList();

            ViewBag.FuturosEstrenos = false;
            var consulta3 = (from t in filter
                             where DateTime.Now < t.StartDate
                             select t).ToList();
            if (consulta1.Count > 0)
            {
                ViewBag.EnCines = true;
            }
            if (consulta2.Count > 0)
            {
                ViewBag.Expiraron = true;
            }
            if (consulta3.Count > 0)
            {
                ViewBag.FuturosEstrenos = true;
            }
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            /*========= cinco mejores =============*/
            var movies = await service.GetAll(n => n.Cinema);
            var cuatroRecientes = (from t in movies
                                   orderby t.Id descending
                                   select t).Take(4).ToList();
            ViewBag.peliculasRecientes = cuatroRecientes;
            var seisRecientes = (from t in movies
                                 orderby t.Id descending
                                 select t).Take(6).ToList();
            ViewBag.peliculasRecientes2 = seisRecientes;

            var details = await service.GetMovieById(id);

            if (details == null)
                return View("NotFound");

            return View(details);
        }

        public async Task<IActionResult> Create()
        {
            var movieDropdown = await service.GetMovieDropDown();

            ViewBag.cinemas = new SelectList(movieDropdown.Cinemas, "Id", "Name");
            ViewBag.producers = new SelectList(movieDropdown.Producers, "Id", "FullName");
            ViewBag.actors = new SelectList(movieDropdown.Actors, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(MovieVM movie)
        {
            if (!ModelState.IsValid)
            {
                var movieDropdown = await service.GetMovieDropDown();

                ViewBag.cinemas = new SelectList(movieDropdown.Cinemas, "Id", "Name");
                ViewBag.producers = new SelectList(movieDropdown.Producers, "Id", "FullName");
                ViewBag.actors = new SelectList(movieDropdown.Actors, "Id", "FullName");

                return View(movie);
            }

            await service.AddMovie(movie);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int id)
        {
            var movie = await service.GetMovieById(id);
            if (movie == null)
                return View("NotFound");

            var response = new MovieVM()
            {
                Id = movie.Id,
                Name = movie.Name,
                Description = movie.Description,
                Price = movie.Price,
                ImagenURL = movie.ImagenURL,
                MovieCategory = movie.MovieCategory,
                StartDate = movie.StartDate,
                EndDate = movie.EndDate,
                CinemaId = movie.CinemaId,
                ProducerId = movie.ProducerId,
                Actors = movie.Actors_Movies.Select(m => m.ActorId).ToList()
            };

            var movieDropdown = await service.GetMovieDropDown();

            ViewBag.cinemas = new SelectList(movieDropdown.Cinemas, "Id", "Name");
            ViewBag.producers = new SelectList(movieDropdown.Producers, "Id", "FullName");
            ViewBag.actors = new SelectList(movieDropdown.Actors, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, MovieVM movie)
        {
            if(id != movie.Id)
                return View("NotFound");

            if (!ModelState.IsValid)
            {
                var movieDropdown = await service.GetMovieDropDown();

                ViewBag.cinemas = new SelectList(movieDropdown.Cinemas, "Id", "Name");
                ViewBag.producers = new SelectList(movieDropdown.Producers, "Id", "FullName");
                ViewBag.actors = new SelectList(movieDropdown.Actors, "Id", "FullName");

                return View(movie);
            }

            await service.UpdateMovie(movie);
            return RedirectToAction(nameof(Index));
        }
        public async Task<ActionResult> DeleteMovies(int id)
        {
            await service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Mirandas-Cinema/Mirandas-Cinema/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Mirandas_Cinema.Data.Cart;
using Mirandas_Cinema.Data.Services;
using Mirandas_Cinema.Data.Static;
using Mirandas_Cinema.Data.ViewModels;
using Mirandas_Cinema.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Mirandas_Cinema.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IMovies service;
        private readonly ShoppingCart cart;
        private readonly IOrders order;
        public OrdersController(IMovies _service, ShoppingCart _cart, IOrders _order)
        {
            service = _service;
            cart = _cart;
            order = _order;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders = await order.GetOrdersUser(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = cart.GetShoppingCartItems();
            cart.ShoppingCartItems = items;

            var response = new ShoppingCartVM() {
                ShoppingCart = cart,
                ShoppingTotal = cart.GetShoppingTotal()
            };

            return View(response);  
        }

        public async Task<IActionResult> AddItem(int id)
        {
            var movie = await service.GetById(id);

            if(movie != null)
            {
                cart.AddItem(movie);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItem(int id)
        {
            var movie = await service.GetById(id);

            if (movie != null)
            {
                cart.RemoveItem(movie);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> Order()
        {
            var movies = cart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string email = User.FindFirstValue(ClaimTypes.Email);

            await order.StoreOrder(movies, userId, email);
            await cart.ClearShoppingCart();

            return View("OrderCompleted"); ;
        }
    }
}

Mirandas-Cinema/Mirandas-Cinema/Views/Shared/NotFound.cshtml
<link href="~/css/page/not-found.css" rel="stylesheet" />

@{
    ViewData["Title"] = "No disponible";
}
<style type="text/css">
    .error-page {
        position: relative;
        top: 0%;
        left: 0%;
        right: 0%;
        bottom: 0%;
        display: flex;
        align-items: center;
        justify-content: center;
        background: #fff;
        box-shadow: 0px 5px 10px rgba(0,0,0,0.1);
        width:90%;
        max-width:1400px;
        margin:auto;
        padding:1em 1em 0 1em;
    }
</style>
<div class="error-page mb-xl-5 rounded">
    <div class="content">
        <h2 class="header title" data-text="404">
            404
        </h2>
        <h4 data-text="Opps! Pagina no encontrada" class="title">
            Pagina no encontrada
        </h4>
        <p class="paragraph">
            Lo sentimos, la página que estás buscando no existe.
        </p>
        <div class="btns">
            <a asp-controller="Movies" asp-action="Index" class="subtitle">Regresar</a>
        </div>
    </div>
</div>

Mirandas-Cinema/Mirandas-Cinema/Views/Shared/_CreateItem.cshtml
@model string;

@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position: fixed; right: 10px; bottom: 10px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success rounded-circle">
            <i class="bi bi-plus" style="font-size:25px"></i>
        </a>
    </div>
}

Mirandas-Cinema/Mirandas-Cinema/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;

    <style type="text/css">
        .dropdown {
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-direction: row;
            gap:0.3em;
        }
    </style>

@if (!User.Identity.IsAuthenticated)
{
<div class="navbar_botones">
    @* Login *@
    <a class="btn btn-success my-2 my-sm-0 nav-item forward mr-1" asp-controller="Account" asp-action="Login">
        <i class="bi bi-person-circle"></i> Login
    </a>

    @* Register *@
    <a class="btn btn-primary my-2 my-sm-0 nav-item forward" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
</div>
}

else
{
    @*Perfil de usuario*@
<div class="dropdown">
    <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-person-square"></i> @*@UserManager.GetUserName(User)*@
    </button>
    <ul class="dropdown-menu" aria-labelledby="profile-btn">
        <li>
            <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                <i class="bi bi-list"></i> Ordenes
            </a>
        </li>
        @if (User.IsInRole("Admin"))
        {
            <li>
                <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                    <i class="bi bi-people"></i> Usuarios
                </a>
            </li>
        }
    </ul>
    @*<span style="padding: 5px;"></span>*@
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> @*Logout*@
        </button>
    </form>
</div>
    @* Logout *@

}

Mirandas-Cinema/Mirandas-Cinema/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mirandas-Cinema</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.1/font/bootstrap-icons.css">
    <link rel="shortcut icon" href="~/icono.ico" width="32px">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="~/css/root/nav-bar-1.css" />
    <link rel="stylesheet" href="~/css/root/nav-bar_queries-2.css" />
    <link href="~/css/root/general.css" rel="stylesheet" />
    <link href="~/css/root/fonts.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/footer/footer.css" />
    <link rel="stylesheet" href="~/css/footer/footer_mediaQueries.css" />
    <style type="text/css">
        .dropdown-menu {
            min-width: 0rem !important;
        }

        .form-inline {
            flex-flow: row !important;
        }

        .dropdown #profile-btn {
            margin: 5px 2px 5px 2px;
        }
    </style>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 nav-links justify-content-center col-md-12">
            <div class="container-fluid">
                <!--Logo-->
                <a class="navbar-brand nav-links" asp-area="" asp-controller="Movies" asp-action="Index"><img src="~/resources/logos/2.png" width="100" /></a>

                <!--boton para pantallas pequeñas-->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" style="position: relative;">
                    <ul class="navbar-nav flex-grow-1 nav-links subtitle querie_column" style="position: relative;">

                        <li class="nav-item forward">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index"><i class="bi bi-house-door"></i> Inicio</a>
                        </li>

                        <li class="nav-item dropdown forward">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                               aria-haspopup="false" aria-expanded="false">
                                <i class="bi bi-film"></i> Categorias
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="padding: 10px;">
                                <i class="bi bi-tag mr-1"></i>@Html.ActionLink("Accion", "Categorias", "Movies", new { categoria = "1" })<br />
                                <i class="bi bi-tag mr-1"></i>@Html.ActionLink("Comedia", "Categorias", "Movies", new { categoria = "2" })<br />
                                <i class="bi bi-tag mr-1"></i>@Html.ActionLink("Romance", "Categorias", "Movies", new { categoria = "3" })<br />
                                <i class="bi bi-tag mr-1"></i>@Html.ActionLink("Terror", "Categorias", "Movies", new { categoria = "4" })<br />
                                <i class="bi bi-tag mr-1"></i>@Html.ActionLink("Animacion", "Categorias", "Movies", new { categoria = "5" })<br />
                            </div>
                        </li>
                        

                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown forward">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                                   aria-haspopup="false" aria-expanded="false">
                                    <i class="bi bi-gear"></i> Administrar
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="padding: 10px;">
                                    <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-headset"></i> Actores</a>
                                    <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"><i class="bi bi-camera-reels"></i> Cines</a>
                                    <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-person-square"></i> Productores</a>
                                </div>
                            </li>
                        }
                        <form class="form-inline my-2 my-lg-0 navbar_form" asp-controller="Movies" asp-action="Filter">
                            <input name="searchMovie" type="text" class="form-control" placeholder="Buscar pelicula..." aria-label="Recipient's username" aria-describedby="button-addon2">&nbsp;
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="max-width: 42px; border-radius: 25%;"><i class="bi bi-search"></i></button>
                        </form>
                    </ul>
                </div>
                &nbsp;
                @* Carrito *@
                <div class="nav-item forward">
                    @await Component.InvokeAsync("ShoppingSummary")
                </div>

                <partial name="_Identity.cshtml" />
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        <main role="main" class="pb-0" style=" margin-bottom: 13em !important;">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted nav-links col-sm-12 nav-footer container justify-content-center contenedor_principal_footer" style="position:absolute;">
        <div class="contenedor_footer">
            <div class="contenedor_nombre_empresa">
                <label class="footer_nombre_empresa">MIRANDA'S<br /> CINEMA</label>
                <a asp-action="Index" asp-controller="Movies">
                    <img src="~/resources/logos/1.png" width="92" />
                </a>
            </div>
            <div class="footer_caja contenedor_footer_info">
                <ul class="footer_info">
                    <li><label class="subtitle">Contáctanos:</label></li>
                    <li> <label class="text-center">Teléfono: 7738 - 8082</label></li>
                    <li><label><a class="text-muted text-center" href="mailto:cinemas@miranda.com">Email: cinemas@mirandas.com</a></label></li>
                </ul>
            </div>

            <div class="footer_caja footer_redes">
                <label class="subtitle">Siguenos en:</label>
                <a href="#">
                    <img src="~/resources/redes/facebook.gif" width="36" />
                </a>
                <a href="#">
                    <img src="~/resources/redes/twitter.gif" width="36" />
                </a>
            </div>
        </div>
        <div style="border:1px solid gainsboro;width:100%;margin-bottom:0.5em;"></div>
        <div class="footer_legal_info">
            <p class="text-center">&copy; 2021 - Mirandas Cinema   </p>
            <a class="text-muted text-center text-decoration-none" href="https://www.privacypolicies.com/live/2a17def5-a250-42b9-b04d-9300683620a3">
                Condiciones de servicio
            </a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!--Carousel-->
    <script src="~/js/jsMovies/js_movies_carousel.js" crossorigin="anonymous"></script>
    <script src="~/js/jsMovies/js_movies_carousel2.js" crossorigin="anonymous"></script>
    <script src="~/js/jsMovies/js_movies_caroucel_3.js" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>