Mirandas-Cinema/Mirandas-Cinema/Controllers/CinemasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mirandas_Cinema.Data;
using Mirandas_Cinema.Data.Services;
using Mirandas_Cinema.Data.Static;
using Mirandas_Cinema.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mirandas_Cinema.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CinemasController : Controller
    {
        private readonly ICinema icinema; 

        public CinemasController(ICinema _cinema)
        {
            icinema = _cinema;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var cinemas = await icinema.GetAll();
            return View(cinemas);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo, Name, Description")] Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }
            else
            {
                await icinema.Add(cinema);
                return RedirectToAction(nameof(Index));
            }
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var details = await icinema.GetById(id);

            if(details == null)
            {
                return View("NotFound");
            }
            else
            {
                return View(details);
            }
        }
        public async Task<IActionResult> Update(int id)
        {
            var updateDetails = await icinema.GetById(id);

            if (updateDetails == null)
            {
                return View("NotFound");
            }
            else
            {
                return View(updateDetails);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id,[Bind("Id, Logo, Name, Description")] Cinema cinema)
        {
            if (!ModelState.IsValid)
            {
                return View(cinema);
            }
            else
            {
                await icinema.Update(id, cinema);
                return RedirectToAction(nameof(Index));
            }
        }
        public async Task<IActionResult> Delete(int id)
        {
            var deleteDetails = await icinema.GetById(id);
            if (deleteDetails == null)
                return View("NoyFound");
            else
                return View(deleteDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var delete = await icinema.GetById(id);
            if (delete == null) return View("NotFound");

            await icinema.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }


}

Mirandas-Cinema/Mirandas-Cinema/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mirandas_Cinema.Data;
using Mirandas_Cinema.Data.Services;
using Mirandas_Cinema.Data.Static;
using Mirandas_Cinema.Data.ViewModels;
using Mirandas_Cinema.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mirandas_Cinema.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class MoviesController : Controller
    {
        private readonly AppDbContext context;
        private IMovies service;

        public MoviesController(AppDbContext _context, IMovies _service)
        {
            context = _context;
            service = _service;
        }

        public ActionResult ControlMovies()
        {
            var peliculas = service.GetMovies();
            return View(peliculas);
        }

        public ActionResult ControlMovie(int interruptor)
        {
            string url = "";
            if (interruptor == 0)
            {
                url = "/Movies/Create";
            }
            return Redirect(url);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index(string searchInvalid, List<Movie> filter)
        {
            var movies = await service.GetAll(n => n.Cinema);
            FiltrarMoviesCaroucel(movies.ToList());

            //para no mostrar los caroucel si no hay resultados
            if (searchInvalid != null && filter.Count == 0)
            {
                movies = filter;
                ViewBag.searchInvalid = searchInvalid;
                FiltrarMoviesCaroucel(filter);

                return View(filter);
            }

            return View(movies);
        }

        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchMovie)
        {
            var movies = await service.GetAll(n => n.Cinema, n => n.Producer);

            if (!string.IsNullOrEmpty(searchMovie))
            {
                //var filter = movies.Where(m => m.Name.ToLower().Contains(searchMovie.ToLower())
                //    || m.Description.ToLower().Contains(searchMovie.ToLower())
                //    || m.Producer.FullName.ToLower().Contains(searchMovie.ToLower())).ToList();

                var filter = movies.Where(m => string.Equals(m.Name, searchMovie,
                    StringComparison.CurrentCultureIgnoreCase) || string.Equals(m.Description, searchMovie,
                    StringComparison.CurrentCultureIgnoreCase) || string.Equals(m.Producer.FullName, searchMovie,
                    StringComparison.CurrentCultureIgnoreCase)).ToList();

                FiltrarMoviesCaroucel(filter);

                if (filter.Count == 0)
                {
                    await Index("No se encontraron resultados...", filter);
                }

                return View("Index", filter);
            }
            return View("Index", movies);
        }

        //Categorias del menu

        [AllowAnonymous]
        public async Task<IActionResult> Categorias(string categoria)
        {
            var movies = await service.GetAll(n => n.Cinema, n => n.Producer);

            //Accion
            if (!categoria.Equals(""))
            {
                var filter = movies.Where(m => m.MovieCategory.GetHashCode()==Convert.ToInt32(categoria)).ToList();

                FiltrarMoviesCaroucel(filter);

                if (filter.Count == 0)
                {
                    await Index("No se encontraron resultados...", filter);
                }

                return View("Index", filter);
            }
            return View("Index", movies);
        }

        //metodo para hacer un filtro en los carouceles y no mostrarlos si en un caroucel no hay peliculas
        public void FiltrarMoviesCaroucel(List<Movie> filter)
        {
            ViewBag.EnCines = false;
            var consulta1 = (from t in filter
                             where DateTime.Now >= t.StartDate && DateTime.Now <= t.EndDate
                             select t).ToList();

            ViewBag.Expiraron = false;
            var consulta2 = (from t in filter
                             where DateTime.Now > t.StartDate && DateTime.Now > t.EndDate
                             select t).ToList();

            ViewBag.FuturosEstrenos = false;
            var consulta3 = (from t in filter
                             where DateTime.Now < t.StartDate
                             select t).ToList();
            if (consulta1.Count > 0)
            {
                ViewBag.EnCines = true;
            }
            if (consulta2.Count > 0)
            {
                ViewBag.Expiraron = true;
            }
            if (consulta3.Count > 0)
            {
                ViewBag.FuturosEstrenos = true;
            }
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            /*========= cinco mejores =============*/
            var movies = await service.GetAll(n => n.Cinema);
            var cuatroRecientes = (from t in movies
                                   orderby t.Id descending
                                   select t).Take(4).ToList();
            ViewBag.peliculasRecientes = cuatroRecientes;
            var seisRecientes = (from t in movies
                                 orderby t.Id descending
                                 select t).Take(6).ToList();
            ViewBag.peliculasRecientes2 = seisRecientes;

            var details = await service.GetMovieById(id);

            if (details == null)
                return View("NotFound");

            return View(details);
        }

        public async Task<IActionResult> Create()
        {
            var movieDropdown = await service.GetMovieDropDown();

            ViewBag.cinemas = new SelectList(movieDropdown.Cinemas, "Id", "Name");
            ViewBag.producers = new SelectList(movieDropdown.Producers, "Id", "FullName");
            ViewBag.actors = new SelectList(movieDropdown.Actors, "Id", "FullName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(MovieVM movie)
        {
            if (!ModelState.IsValid)
            {
                var movieDropdown = await service.GetMovieDropDown();

                ViewBag.cinemas = new SelectList(movieDropdown.Cinemas, "Id", "Name");
                ViewBag.producers = new SelectList(movieDropdown.Producers, "Id", "FullName");
                ViewBag.actors = new SelectList(movieDropdown.Actors, "Id", "FullName");

                return View(movie);
            }

            await service.AddMovie(movie);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int id)
        {
            var movie = await service.GetMovieById(id);
            if (movie == null)
                return View("NotFound");

            var response = new MovieVM()
            {
                Id = movie.Id,
                Name = movie.Name,
                Description = movie.Description,
                Price = movie.Price,
                ImagenURL = movie.ImagenURL,
                MovieCategory = movie.MovieCategory,
                StartDate = movie.StartDate,
                EndDate = movie.EndDate,
                CinemaId = movie.CinemaId,
                ProducerId = movie.ProducerId,
                Actors = movie.Actors_Movies.Select(m => m.ActorId).ToList()
            };

            var movieDropdown = await service.GetMovieDropDown();

            ViewBag.cinemas = new SelectList(movieDropdown.Cinemas, "Id", "Name");
            ViewBag.producers = new SelectList(movieDropdown.Producers, "Id", "FullName");
            ViewBag.actors = new SelectList(movieDropdown.Actors, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, MovieVM movie)
        {
            if(id != movie.Id)
                return View("NotFound");

            if (!ModelState.IsValid)
            {
                var movieDropdown = await service.GetMovieDropDown();

                ViewBag.cinemas = new SelectList(movieDropdown.Cinemas, "Id", "Name");
                ViewBag.producers = new SelectList(movieDropdown.Producers, "Id", "FullName");
                ViewBag.actors = new SelectList(movieDropdown.Actors, "Id", "FullName");

                return View(movie);
            }

            await service.UpdateMovie(movie);
            return RedirectToAction(nameof(Index));
        }
        public async Task<ActionResult> DeleteMovies(int id)
        {
            await service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Mirandas-Cinema/Mirandas-Cinema/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Mirandas_Cinema.Data.Cart;
using Mirandas_Cinema.Data.Services;
using Mirandas_Cinema.Data.Static;
using Mirandas_Cinema.Data.ViewModels;
using Mirandas_Cinema.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Mirandas_Cinema.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IMovies service;
        private readonly ShoppingCart cart;
        private readonly IOrders order;
        public OrdersController(IMovies _service, ShoppingCart _cart, IOrders _order)
        {
            service = _service;
            cart = _cart;
            order = _order;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);
            var orders = await order.GetOrdersUser(userId, userRole);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = cart.GetShoppingCartItems();
            cart.ShoppingCartItems = items;

            var response = new ShoppingCartVM() {
                ShoppingCart = cart,
                ShoppingTotal = cart.GetShoppingTotal()
            };

            return View(response);  
        }

        public async Task<IActionResult> AddItem(int id)
        {
            var movie = await service.GetById(id);

            if(movie != null)
            {
                cart.AddItem(movie);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> RemoveItem(int id)
        {
            var movie = await service.GetById(id);

            if (movie != null)
            {
                cart.RemoveItem(movie);
            }

            return RedirectToAction(nameof(ShoppingCart));
        }

        public async Task<IActionResult> Order()
        {
            var movies = cart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string email = User.FindFirstValue(ClaimTypes.Email);

            await order.StoreOrder(movies, userId, email);
            await cart.ClearShoppingCart();

            return View("OrderCompleted"); ;
        }
    }
}

Mirandas-Cinema/Mirandas-Cinema/Controllers/ProducersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mirandas_Cinema.Data;
using Mirandas_Cinema.Data.Services;
using Mirandas_Cinema.Data.Static;
using Mirandas_Cinema.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mirandas_Cinema.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProducersController : Controller
    {
        private readonly IProducer iproducers;

        public ProducersController(IProducer _producers)
        {
            iproducers = _producers;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var cinemas = await iproducers.GetAll();
            return View(cinemas);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var deleteDetails = await iproducers.GetById(id);
            if (deleteDetails == null)
                return View("NoyFound");
            else
                return View(deleteDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var delete = await iproducers.GetById(id);
            if (delete == null) return View("NotFound");

            await iproducers.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfilePictureURL, FullName, Bio")] Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }
            else
            {
                await iproducers.Add(producer);
                return RedirectToAction(nameof(Index));
            }
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var details = await iproducers.GetById(id);

            if (details == null)
            {
                return View("NotFound");
            }
            else
            {
                return View(details);
            }

        }

        public async Task<IActionResult> Edits(int id)
        {

            var updateDetails = await iproducers.GetById(id);

            if (updateDetails == null)
                return View("NotFound");
            else
                return View(updateDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edits(int id, [Bind("Id, ProfilePictureURL, FullName, Bio")] Producer producer)
        {
            if (!ModelState.IsValid)
            {
                return View(producer);
            }

            else
            {
                await iproducers.Update(id, producer);
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

Mirandas-Cinema/Mirandas-Cinema/Views/Movies/Details.cshtml
@model Movie
@{
    ViewData["Title"] = "Detalles pelicula";
}

<link rel="stylesheet" href="~/css/movies/aside_detail.css" />
<link rel="stylesheet" href="~/css/movies/aside_media_querie.css" />

<div class="principal">
    <div class="bg-white aside_main_container">
        <div class="font-weight-bolder">
            <label class="text-center title">Peliculas recientes</label>
        </div>
        <div class="aside_one_container">
            <div>
                @foreach (var i in @ViewBag.peliculasRecientes)
                {
                    <div class="aside_three_container">
                        <a asp-action="Details" asp-route-id="@i.Id">
                            <img src="@i.ImagenURL" alt="Peliculas recientes" class="img-fluid col-auto pelicula_hover img-thumbnail" />
                        </a>
                    </div>
                }
            </div>
        </div>
    </div>
    <!----------------------------------------------------------------->
    <div class="row nav-links medidas col-md-9 mt-0 @*ml-auto*@ mr-auto_custome @*mb-xl-5*@ bg-white">
        <!----------------------------------------------------------------->
        <div class="col-md-8_custome bg-white" style="margin: 1.3em auto !important;">
            <div class="card m-auto" style="max-width: 600px">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-primary">
                            <p class="card-text">
                                <h5 class="card-title title">
                                    @Model.Name
                                </h5>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 img_detalles">
                    <img src="@Model.ImagenURL" alt="@Model.Name" width="100%" />
                </div>
                <div class="col-md-12 float-left">
                    <div class="card-body">
                        <div @*style="max-height: 100px;"*@ class="mb-5">
                            <p class="card-text">@Model.Description</p>
                        </div>
                        <p class="card-text">
                            <b>Cine:</b>
                            <a asp-controller="Cinemas" asp-action="Details" asp-route-id="@Model.CinemaId">
                                @Model.Cinema.Name
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Productor:</b>
                            <a asp-controller="Producers" asp-action="Details" asp-route-id="@Model.ProducerId">
                                @Model.Producer.FullName
                            </a>
                        </p>
                        <p class="card-text"><b>Categoria:</b> @Model.MovieCategory</p>
                        <p class="card-text"><b>Inicio:</b> @Model.StartDate.ToString("dd MMMM yy")</p>
                        <p class="card-text"><b>Finalizacion:</b> @Model.EndDate.ToString("dd MMMM yy")</p>
                        <p class="card-text">
                            <b>Estado: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">Disponible</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">Expirada</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">Muy pronto</span>
                            }
                        </p>

                        <p class="card-text">
                            <b>Actores:</b>
                            <hr />
                            <div class="row">
                                @foreach (var actor in Model.Actors_Movies)
                                {
                                    <div class="col-md-3 column text-center">
                                        <img class="border-info rounded-circle" src="@actor.Actor.ProfilePictureURL" style="min-width: 100px; max-width: 100px;" />
                                        <br />
                                        <a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.Actor.Id">@actor.Actor.FullName</a>
                                    </div>
                                }
                            </div>
                        </p>
                    </div>
                </div>

                <div class="col-md-12">
                    <div class="card-footer mb-3">
                        <p class="card-text">
                            <a class="btn btn-success text-white float-right @((DateTime.Now > Model.EndDate) ? "disabled" : "")" asp-controller="Orders" asp-action="AddItem" asp-route-id="@Model.Id">
                                <i class="bi bi-cart-plus"></i> Agregar (@Model.Price.ToString("c"))
                            </a>&nbsp;
                            <a class="btn btn-primary text-white float-left" asp-action="Index">
                                Mostrar todos
                            </a>
                        </p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<!--=============================================-->
<div class="color_pelis_recientes bg-white">
    <div class="contenedor_aside_2">
        <h5>Peliculas recientes</h5>
        <div class="contenedor_aside_img_2">
            @foreach (var i in @ViewBag.peliculasRecientes2)
            {
                <a asp-action="Details" asp-route-id="@i.Id" class="pelicula_hover">
                    <img src="@i.ImagenURL" alt="Peliculas recientes" class="img-thumbnail" style="width:100%;" />
                </a>

            }
        </div>
    </div>
</div>
<!--=============================================-->

Mirandas-Cinema/Mirandas-Cinema/Views/Movies/Index.cshtml
0
<link rel="stylesheet" href="~/css/movies/Movies_carousel.css" />
<link rel="stylesheet" href="~/css/movies/movies_carousel_mediaQueries.css" />
<link rel="stylesheet" href="~/css/movies/container_main_index.css" />
<link rel="stylesheet" href="~/css/movies/main_container_queries.css" />

@model IEnumerable<Movie>

@{
    ViewData["Title"] = "Movies";
}
<!--    CAROUSEL    -->
<!--SOLO EN CINES-->
@if (@ViewBag.EnCines == true)
{
    <div class="caja_contenedor contenedor_peliculas_recomendadas bg-white">
        <div class="contenedor_titulo_controles">
            <h3 class="title">En emisión</h3>
            <div class="indicadores indicadores1">

            </div>
        </div>

        <div class="contenedor_pricipal">
            <button role="button" id="flecha_izquierda1" class="flecha_izquierda" type="button"><i class="fas fa-angle-left"></i></button>

            <div class="contenedor_carousel contenedor_carousel">

                <div class="carousel carousel1">


                    @foreach (var item in Model)
                    {
                        @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                        {
                            <div class="pelicula pelicula1 col-md-2">
                                <a asp-action="Details" asp-route-id="@item.Id">
                                    <img src="@item.ImagenURL" alt="pelicula" style="width:100%;" />

                                </a>
                                <span class="pelicula_nombre">@item.Name</span>
                            </div>
                        }

                    }

                </div>

            </div>

            <button role="button" id="flecha_derecha1" class="flecha_derecha"><i class="fas fa-angle-right"></i></button>
        </div>
    </div>
}

<!--EXPIRARON-->
@if (@ViewBag.Expiraron == true)
{
    <div class="caja_contenedor contenedor_peliculas_recomendadas bg-white">
        <div class="contenedor_titulo_controles">
            <h3 class="title">Expiradas recientemente</h3>
            <div class="indicadores indicadores2">

            </div>
        </div>

        <div class="contenedor_pricipal">
            <button role="button" id="flecha_izquierda2" class="flecha_izquierda" type="button"><i class="fas fa-angle-left"></i></button>

            <div class="contenedor_carousel contenedor_carousel2">

                <div class="carousel carousel2">


                    @foreach (var item in Model)
                    {
                        @if (DateTime.Now > item.StartDate && DateTime.Now > item.EndDate)
                        {
                            <div class="pelicula pelicula2 col-md-2">
                                <a asp-action="Details" asp-route-id="@item.Id">
                                    <img src="@item.ImagenURL" alt="pelicula" style="width:100%;" />

                                </a>
                                <span class="pelicula_nombre">@item.Name</span>
                            </div>
                        }

                    }

                </div>

            </div>

            <button role="button" id="flecha_derecha2" class="flecha_derecha"><i class="fas fa-angle-right"></i></button>
        </div>
    </div>
}

<!--Futuros estrenos-->
@if (@ViewBag.FuturosEstrenos == true)
{

    <div class="caja_contenedor contenedor_peliculas_recomendadas bg-white">
        <div class="contenedor_titulo_controles">
            <h3 class="title">Próximos estrenos</h3>
            <div class="indicadores indicadores3">

            </div>
        </div>

        <div class="contenedor_pricipal">
            <button role="button" id="flecha_izquierda3" class="flecha_izquierda flecha_izquierda3" type="button"><i class="fas fa-angle-left"></i></button>

            <div class="contenedor_carousel contenedor_carousel3">

                <div class="carousel carousel3">


                    @foreach (var item in Model)
                    {
                        @if ((DateTime.Now < item.StartDate))
                        {
                            <div class="pelicula pelicula3 col-md-2">
                                <a asp-action="Details" asp-route-id="@item.Id">
                                    <img src="@item.ImagenURL" alt="pelicula" style="width:100%;" />

                                </a>
                                <span class="pelicula_nombre">@item.Name</span>
                            </div>
                        }

                    }

                </div>

            </div>

            <button role="button" id="flecha_derecha3" class="flecha_derecha"><i class="fas fa-angle-right"></i></button>
        </div>
    </div>
}
<!--===============================================-->

@if (@ViewBag.searchInvalid != null)
{
    <div class="bg-white no_resultados">
        <p class="not-results">
            @ViewBag.searchInvalid
        </p>

    </div>
}

@if (@ViewBag.searchInvalid == null)
{
    <div class="container_main_index bg-white">


        @foreach (var movie in Model)
        {
            <div class="container_one_index">


                <h5 class="bg-bgtitle text-white container_titulo">
                    <label class="titulo">@movie.Name</label>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <a class="text-white float-right" asp-action="Update" asp-route-id="@movie.Id"><i class="bi bi-pencil-square"></i></a>
                        <a class="text-white float-right" asp-action="DeleteMovies" asp-controller="Movies" asp-route-id="@movie.Id"><i class="fas fa-trash-alt"></i></a>
                    }
                </h5>

                <div class="col-md-9 m-auto">
                    <img src="@movie.ImagenURL" alt="@movie.Name" width="100%" />
                </div>
                <div class="col-md-12">
                    <div class="card-body">
                        <p class="card-text"><b>Cine:</b> @movie.Cinema.Name</p>
                        <p class="card-text"><b>Inicio:</b> @movie.StartDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>Finalizacion:</b> @movie.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text">
                            <b>Estado: </b>
                            @if (DateTime.Now >= movie.StartDate && DateTime.Now <= movie.EndDate)
                            {
                                <span class="badge bg-success text-white">Disponible</span>
                            }
                            else if (DateTime.Now > movie.EndDate)
                            {
                                <span class="badge bg-danger text-white">Expirada</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">Muy pronto</span>
                            }
                        </p>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text botones_tarjeta">
                            <a class="btn btn-outline-primary boton_tarjeta" asp-action="Details" asp-route-id="@movie.Id">
                                <i class="bi bi-eye-fill">
                                </i> Detalles
                            </a>
                            <a class="btn btn-success text-white @((DateTime.Now > movie.EndDate) ? "disabled" : "") boton_tarjeta" asp-controller="Orders" asp-action="AddItem" asp-route-id="@movie.Id">
                                <i class="bi bi-cart-plus"></i> Añadir (@movie.Price.ToString("c"))
                            </a>&nbsp;

                            @await Html.PartialAsync("_CreateItem", "Movies")
                        </p>
                    </div>
                </div>

            </div>
        }
    </div>
}